services:
  redis:
    image: redis:latest
    command: redis-server --requirepass default
    environment:
      REDIS_PASSWORD: default
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    environment:
      N8N_HOST: vizzusolu.duckdns.org
      N8N_PORT: 5678
      WEBHOOK_URL: https://vizzusolu.duckdns.org/
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug

      # database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: default
      DB_POSTGRESDB_USER: default
      DB_POSTGRESDB_PASSWORD: default

      # redis sessions
      N8N_ENABLE_SESSION_STORAGE: "true"
      N8N_SESSION_STORAGE_TYPE: redis
      N8N_REDIS_HOST: redis
      N8N_REDIS_PORT: 6379
      N8N_REDIS_PASSWORD: default

    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
  n8n_data:

