n8n:
    image: n8nio/n8n:latest
    platform: linux/amd64
    environment:

      WEBHOOK_URL: https://vizzusolu.duckdns.org/
      
      N8N_PATH: /n8n/
      
      VUE_APP_BASE_URL: /n8n/
      
      N8N_HOST: 0.0.0.0
      

      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
      N8N_PACKAGES_INCLUDE: n8n-nodes-evolution-api
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    extra_hosts:
